apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-app-canary-deployment
  labels:
    app: car-app
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-app
      track: canary
  template:
    metadata:
      labels:
        app: car-app
        track: canary
    spec:
      containers:
        - name: car-app
          image: shaliga/car-image:latest
          ports:
            - containerPort: 3000
