apiVersion: v1
kind: Service
metadata:
  name: car-app-service
spec:
  type: ClusterIP
  selector:
    app: car-app
  ports:
    - protocol: TCP
      port: 3000       # External service port
      targetPort: 3000 # Port used by the app inside the pod
