apiVersion: v1
kind: Service
metadata:
  name: car-app-service
spec:
  type: NodePort
  selector:
    app: car-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001  
